# Generated by Django 6.0.1 on 2026-04-20 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='About Me', max_length=200)),
                ('subtitle', models.CharField(default='Full Stack Developer', max_length=200)),
                ('description', models.TextField()),
                ('professional_summary', models.TextField()),
                ('cv_file', models.FileField(blank=True, null=True, upload_to='cv/')),
            ],
            options={
                'verbose_name_plural': 'About Info',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('link', models.URLField(blank=True, default='#')),
                ('order', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('percent', models.IntegerField(default=0)),
                ('category', models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend')], max_length=20)),
            ],
        ),
    ]
